name: SwiftPM

on:
  push:
    branches: [ tmp ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ tmp ]

jobs:
  build:
    runs-on: emcee-macos-14

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
